In [1]:
from HubbardHF import Hubb
import numpy as np

In [2]:
Nx    = 4
Ny    = 4
NAO   = Nx*Ny
NOccA = 8
NOccB = 8
TT    = 1.0
U     = 4.0
tol   = 1e-9
PBCx  = True
PBCy  = True
dmp   = 0.

In [3]:
HF = Hubb(Nx,Ny,NOccA,NOccB,U,tol)
HF.mkHopping(PBCx,PBCy)
print(HF.T)
#HF.mkGuess(addCore=0.5,addNeel=0.5)
#HF.setupDIIS(Ninit = 5, NDIIS = 5)
#HF.doSCF(damping  = dmp, doDIIS = True)
#print(HF.Energy/(Nx*Ny))

[[ 0. -1.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.]
 [-1.  0. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [-1.  0. -1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0. -1.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  0. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. -1.  0. -1.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1. -1.  0. -1.  0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0. -1.  0. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0. -1.  0. -1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  0. -1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1. -1.  0. -1.  0.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0. -1.  0. -1.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  0. 

In [4]:
type(mat)

NameError: name 'mat' is not defined